---
# supported frameworks: mocha|jest|jasmine
framework: mocha

# provide the semantic version of nodejs required for your project
nodeVersion: 14.17.2

# configure whether to smartSelect test-cases. Default true
smartRun: false

# supported tiers: xmall|small|medium|large|xlarge
tier: xsmall

# number of containers in which the tests must be splitted into for execution
parallelism: 2

# version of tas file intended to be used in order to issue warnings for deprecation or breaking changes
version: 2.0
