---
framework: jest
postMerge:
  pattern:
    - './src/**/*.spec.ts'
preMerge:
  pattern:
    - './src/**/*.spec.ts'
preRun:
  command:
    - npm ci
postRun:
  command:
    - node --version
parallelism: 2
version: 2.0


